version: "3"

services:
  django:
    image: hub.pandoraresearch.com/demo
  env_file:
    - ./.env.compose

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env.db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/demo-tasks/db-data

