name: build-service
on:
  workflow_call:
    inputs:
      hub_host:
        description: 'docker registry hub'
        type: string
        required: true
      hub_user:
        description: 'user for docker registry hub'
        type: string
        required: true
    secrets:
      hub_pass:
        description: 'password for docker registry hub'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: fetch tags
        run: git fetch --tags origin
      - name: set RELEASE_VERSION env
        run: echo "RELEASE_VERSION="$(git tag --sort=-version:refname | head -n 1)"" >> $GITHUB_ENV
      - name: check RELEASE_VERSION
        run: echo $RELEASE_VERSION
      - name: docker login
        run: docker login --username $HUB_USER --password $HUB_PASS $HUB_HOST
        env:
          HUB_HOST: ${{ vars.hub_host }}
          HUB_USER: ${{ vars.hub_user }}
          HUB_PASS: ${{ secrets.hub_pass }}
      - name: build service
        run: make build ver=$RELEASE_VERSION
