name: deploy-service
on:
  push:
    branches:
      - master
jobs:
  lint:
    uses: inikishin/ci-cd/.github/workflows/lint.yml@master
  test:
    uses: inikishin/ci-cd/.github/workflows/test.yml@master
  build:
    needs: [lint, test]
    uses: inikishin/ci-cd/.github/workflows/build.yml@master
    with:
      hub_user: ${{ vars.HUB_USER }}
      hub_host: ${{ vars.HUB_HOST }}
    secrets:
      hub_pass: ${{ secrets.HUB_PASS }}
  restart:
    needs: [build]
    uses: inikishin/ci-cd/.github/workflows/restart.yml@master
    with:
      ssh_user: ${{ vars.SSH_USER }}
      ssh_host: ${{ vars.SSH_HOST }}
      ssh_project_path: ${{ vars.SSH_PROJECT_PATH }}
    secrets:
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
