name: deploy-service
on:
  push:
    tags:
      - 'v*.*'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Lint service..."
      - run: make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Testing service..."
      - run: make test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start echo
        run: echo "Build service..."
      - run: ${GITHUB_REF}"
      - name: Set RELEASE_VERSION env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - run: echo "Push service to hub..."
      - run: make build
  restart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Restart service..."
      - run: make deploy
