name: restart-service
on: [workflow_dispatch]
jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello world"
      - run: ls -lah
      - run: make restart
