name: set-version
on: [workflow_dispatch]
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: fetch tags
        run: git fetch --tags origin
      - name: set RELEASE_VERSION env
        run: echo "RELEASE_VERSION="$(git tag --sort=-version:refname | head -n 1)"" >> $GITHUB_ENV
      - name: check RELEASE_VERSION
        run: echo $RELEASE_VERSION
