name: set-version
on: [workflow_dispatch]
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "$VER_BUILD"
        env:
          VER_BUILD: ${{ vars.VER_BUILD }}
